name: Convert Markdown to PDF

on:
  workflow_dispatch: # Allows you to manually trigger the workflow from the Actions tab
  push:
    paths:
      - "*.md" # Runs the workflow if any markdown file is pushed or updated
  pull_request:
    paths:
      - "*.md" # Runs the workflow on PRs with markdown file changes

jobs:
  convert_to_pdf:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Pandoc
      run: sudo apt-get install -y pandoc

    - name: Convert Markdown to PDF
      run: |
        mkdir -p output
        for file in *.md; do
          pandoc "$file" -o "output/${file%.md}.pdf"
        done

    - name: Upload PDF
      uses: actions/upload-artifact@v3
      with:
        name: PDF-Files
        path: output/
